### ISSUE TITLE
Question: threshold_to_filter - incomplete quantifications

### ISSUE THREAD

**Issue by patrick-willems** [jessegmeyerlab/PeCorA#4]
Best,

I am very excited to use PeCorA for re-analysing some data, the following is rather a question than an issue:

Is there a way to retrieve discordant peptides that have missing values in certain replicates? I am using DDA-based quantifications (with 5 replicates) and noted that all my significant peptides have 5 quantifications. Now, does this have anything to do with the 'threshold_to_filter' parameter (I could not immediately find documentation on it - or I missed it). Anyhow, I don't know whether it is (statistically) possible to retrieve discordant peptides that are not necessarily quantified in every replicate? I just have the feeling I might miss out on some interesting leads with my current results.

Thanks in advance,
Patrick

**Comment by jgmeyerucsd** [comment]
Thanks for trying pecora!

Currently there is no way that you could look at peptides without quantities in all the replicates. Those peptides are removed before the main analysis. I'm not sure if it would be compatible with the linear model if there were different numbers of quantities for each group. 

On a related note, in my experience, I never finished a large scale analysis and felt like I didn't have enough hits to explore.

Best,
Jesse
